# Generated by Django 3.1.6 on 2021-07-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='instraction',
            new_name='instruction',
        ),
    ]
