# Generated by Django 3.1.6 on 2021-07-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_auto_20210708_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
